### PR TITLE
Dynamic config registry

### PR DESCRIPTION
**Pull request by Gegy**
Draft for now, to be integrated with a future breaking release.

### CODE REVIEW

**Comment by Hugman76** [comment]
We can now use Fabric API 0.86.1+ for registering dynamic registries:
```java
import net.fabricmc.fabric.api.event.registry.DynamicRegistries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.RegistryKey;

public class MyRegistryKeys {
    public static final RegistryKey<Registry<Bar>> BAR = RegistryKey.ofRegistry(new Identifier("foo", "bar"));

    public static void register() {
        DynamicRegistries.register(BAR, Bar.CODEC);
    }
}
```

**Comment by Hugman76** [comment]
Why are game portals still managed by their own class rather than a dynamic registry?

**Comment by Gegy** [comment]
No specific reason here - definitely something that can and should be done, just needs a bit more work than configs 🙂

**Comment by Hugman76** [comment]
Okay then let's leave that to another PR I think
But we might want to get it in 0.6 too

**Review by Hugman76 — APPROVED** [review]

**Comment by Hugman76** [comment]
Also as a side note: using FAPI dynamic resistry will have to make us move all `data/games` folders to `data/plasmid/games`

**Pull request merged**
