### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [NucleoidMC/Plasmid](https://hosted.weblate.org/projects/nucleoid/plasmid/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by arthurbambou** [comment]
Merge when?

**Review by ashhhleyyy — APPROVED** [review]

**Comment by ashhhleyyy** [comment]
I can merge it now, but some of the filenames will need correcting afterwards

**Comment by arthurbambou** [comment]
ServerTranslationAPI should be still able to handle them.

**Comment by ashhhleyyy** [comment]
even the one with the `@`?

**Comment by arthurbambou** [comment]
Yeah normally

**Comment by arthurbambou** [comment]
We can always fix it later if necessary.

**Pull request merged**
